spring:
  application:
    name: moneytransfer
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect