DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID VARCHAR(150) NOT NULL UNIQUE,
  CURRENCY VARCHAR(30) NOT NULL,
  BALANCE DOUBLE DEFAULT 0
);

INSERT INTO ACCOUNT(ACCOUNT_ID, CURRENCY, BALANCE) VALUES ('1', 'EUR', 3000);
INSERT INTO ACCOUNT(ACCOUNT_ID, CURRENCY, BALANCE) VALUES ('2', 'EUR', 0);
